`default_nettype none
// PLEASE READ THIS, IT MAY SAVE YOU SOME TIME AND MONEY, THANK YOU!
// * This file was generated by Quokka FPGA Toolkit.
// * Generated code is your property, do whatever you want with it
// * Place custom code between [BEGIN USER ***] and [END USER ***].
// * CAUTION: All code outside of [USER] scope is subject to regeneration.
// * Bad things happen sometimes in developer's life,
//   it is recommended to use source control management software (e.g. git, bzr etc) to keep your custom code safe'n'sound.
// * Internal structure of code is subject to change.
//   You can use some of signals in custom code, but most likely they will not exist in future (e.g. will get shorter or gone completely)
// * Please send your feedback, comments, improvement ideas etc. to evmuryshkin@gmail.com
// * Visit https://github.com/EvgenyMuryshkin/QuokkaEvaluation to access latest version of playground
// 
// DISCLAIMER:
//   Code comes AS-IS, it is your responsibility to make sure it is working as expected
//   no responsibility will be taken for any loss or damage caused by use of Quokka toolkit.
// 
// System configuration name is Arrays_TopLevel, clock frequency is 1Hz, Top-level
// FSM summary
// -- Packages
module Enc (
// [BEGIN USER PORTS]
// [END USER PORTS]

	input [31: 0] Counter,
	output Or,
	output And,
	output Xor,
	output [4: 0] Enc
    );
    
    
reg tmpOr = 1'b0;
reg tmpAnd = 1'b0;
reg tmpXor = 1'b0;
integer i;

always @(*)
begin
	tmpOr = 0;
	tmpAnd = 1;
	tmpXor = 0;
	for (i = 0; i < 32; i = i + 1) 
	begin
		tmpOr = tmpOr | Counter[i];
		tmpAnd = tmpAnd & Counter[i];
		tmpXor = tmpXor ^ Counter[i];
	end
end
assign Or = tmpOr;
assign And = tmpAnd;
assign Xor = tmpXor;

endmodule