cd QuokkaCLI
dotnet run -s "../FunctionalTest/vhdl.json"
dotnet run -s "../FunctionalTest/verilog.json"
dotnet run -s "../KeccakTest/vhdl.json"
dotnet run -s "../KeccakTest/verilog.json"
dotnet run -s "../SnakeGame/vhdl.json"
dotnet run -s "../SnakeGame/verilog.json"
dotnet run -s "../SensorsBoard/Device/vhdl.json"
dotnet run -s "../SensorsBoard/Device/verilog.json"
dotnet run -s "../BumperHero/BHDevice/vhdl.json"
dotnet run -s "../BumperHero/BHDevice/verilog.json"
dotnet run -s "../SunTracker/SunTrackerDevice/vhdl.json"
dotnet run -s "../SunTracker/SunTrackerDevice/verilog.json"
dotnet run -s "../Fourier/vhdl.json"
dotnet run -s "../Fourier/verilog.json"
dotnet run -s "../OrbitalCalc/FPGA.OrbitalCalc.Controllers/vhdl.json"
dotnet run -s "../OrbitalCalc/FPGA.OrbitalCalc.Controllers/verilog.json"
dotnet run -s "../Trigonometry/FPGA.Trigonometry.Controllers/vhdl.json"
dotnet run -s "../Trigonometry/FPGA.Trigonometry.Controllers/verilog.json"
cd ..
