-- PLEASE READ THIS, IT MAY SAVE YOU SOME TIME AND MONEY, THANK YOU!
-- * This file was generated by Quokka FPGA Toolkit.
-- * Generated code is your property, do whatever you want with it
-- * Place custom code between [BEGIN USER ***] and [END USER ***].
-- * CAUTION: All code outside of [USER] scope is subject to regeneration.
-- * Bad things happen sometimes in developer's life,
--   it is recommended to use source control management software (e.g. git, bzr etc) to keep your custom code safe'n'sound.
-- * Internal structure of code is subject to change.
--   You can use some of signals in custom code, but most likely they will not exist in future (e.g. will get shorter or gone completely)
-- * Please send your feedback, comments, improvement ideas etc. to evmuryshkin@gmail.com
-- * Visit https://github.com/EvgenyMuryshkin/QuokkaEvaluation to access latest version of playground
-- 
-- DISCLAIMER:
--   Code comes AS-IS, it is your responsibility to make sure it is working as expected
--   no responsibility will be taken for any loss or damage caused by use of Quokka toolkit.
-- 
-- System configuration name is XorGateModule_TopLevel, clock frequency is 1Hz, Top-level
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

use work.Quokka.all;

entity XorGateModule_TopLevel is
    port
    (
-- [BEGIN USER PORTS]
-- [END USER PORTS]

XorGateModuleI1 : in  std_logic;
XorGateModuleI2 : in  std_logic;
XorGateModuleO : out  std_logic
    );
end entity;

-- FSM summary
-- Packages
architecture rtl of XorGateModule_TopLevel is
-- [BEGIN USER SIGNALS]
-- [END USER SIGNALS]
constant HiSignal : std_logic := '1';
constant LoSignal : std_logic := '0';
signal XorGateModule_TopLevel_XorGateModuleI1 : std_logic := '0';
signal XorGateModule_TopLevel_XorGateModuleI2 : std_logic := '0';
signal XorGateModule_TopLevel_XorGateModuleO : std_logic := '0';
signal XorGateModule_TopLevel_XorGateModule_I1 : std_logic := '0';
signal XorGateModule_TopLevel_XorGateModule_I2 : std_logic := '0';
signal XorGateModule_TopLevel_XorGateModule_O : std_logic := '0';
constant XorGateModule_TopLevel_XorGateModule_Zero : std_logic := '0';
constant XorGateModule_TopLevel_XorGateModule_One : std_logic := '1';
constant XorGateModule_TopLevel_XorGateModule_true : std_logic := '1';
constant XorGateModule_TopLevel_XorGateModule_false : std_logic := '0';
signal XorGateModule_TopLevel_XorGateModule_Inputs_I1 : std_logic := '0';
signal XorGateModule_TopLevel_XorGateModule_Inputs_I2 : std_logic := '0';
signal XorGateModule_TopLevel_XorGateModule_SimpleGates_L22F26T47_Expr : std_logic := '0';
signal XorGateModule_TopLevel_XorGateModule_SimpleGates_L22F26T47_Expr_1 : std_logic := '0';
signal XorGateModule_TopLevel_XorGateModule_SimpleGates_L22F26T47_Expr_2 : std_logic := '0';
begin

process(XorGateModule_TopLevel_XorGateModule_SimpleGates_L22F26T47_Expr_1, XorGateModule_TopLevel_XorGateModule_SimpleGates_L22F26T47_Expr_2)
begin
XorGateModule_TopLevel_XorGateModule_SimpleGates_L22F26T47_Expr <= XorGateModule_TopLevel_XorGateModule_SimpleGates_L22F26T47_Expr_1 XOR XorGateModule_TopLevel_XorGateModule_SimpleGates_L22F26T47_Expr_2;

    end process;
-- Top-level entity connections
process(XorGateModule_TopLevel_XorGateModuleO, XorGateModuleI1, XorGateModuleI2)
begin
	XorGateModule_TopLevel_XorGateModuleI1 <= XorGateModuleI1;
	XorGateModule_TopLevel_XorGateModuleI2 <= XorGateModuleI2;
XorGateModuleO <= XorGateModule_TopLevel_XorGateModuleO;
end process;
process(XorGateModule_TopLevel_XorGateModule_I1, XorGateModule_TopLevel_XorGateModule_I2, XorGateModule_TopLevel_XorGateModule_Inputs_I1, XorGateModule_TopLevel_XorGateModule_Inputs_I2, XorGateModule_TopLevel_XorGateModule_O, XorGateModule_TopLevel_XorGateModule_SimpleGates_L22F26T47_Expr, XorGateModule_TopLevel_XorGateModuleI1, XorGateModule_TopLevel_XorGateModuleI2)
begin
XorGateModule_TopLevel_XorGateModule_I1 <= XorGateModule_TopLevel_XorGateModuleI1;
XorGateModule_TopLevel_XorGateModule_I2 <= XorGateModule_TopLevel_XorGateModuleI2;
XorGateModule_TopLevel_XorGateModuleO <= XorGateModule_TopLevel_XorGateModule_O;
XorGateModule_TopLevel_XorGateModule_SimpleGates_L22F26T47_Expr_1 <= XorGateModule_TopLevel_XorGateModule_Inputs_I1;
XorGateModule_TopLevel_XorGateModule_SimpleGates_L22F26T47_Expr_2 <= XorGateModule_TopLevel_XorGateModule_Inputs_I2;
XorGateModule_TopLevel_XorGateModule_Inputs_I1 <= XorGateModule_TopLevel_XorGateModule_I1;
XorGateModule_TopLevel_XorGateModule_Inputs_I2 <= XorGateModule_TopLevel_XorGateModule_I2;
XorGateModule_TopLevel_XorGateModule_O <= XorGateModule_TopLevel_XorGateModule_SimpleGates_L22F26T47_Expr;
end process;
-- [BEGIN USER ARCHITECTURE]
-- [END USER ARCHITECTURE]
end architecture;
