`default_nettype none
// PLEASE READ THIS, IT MAY SAVE YOU SOME TIME AND MONEY, THANK YOU!
// * This file was generated by Quokka FPGA Toolkit.
// * Generated code is your property, do whatever you want with it
// * Place custom code between [BEGIN USER ***] and [END USER ***].
// * CAUTION: All code outside of [USER] scope is subject to regeneration.
// * Bad things happen sometimes in developer's life,
//   it is recommended to use source control management software (e.g. git, bzr etc) to keep your custom code safe'n'sound.
// * Internal structure of code is subject to change.
//   You can use some of signals in custom code, but most likely they will not exist in future (e.g. will get shorter or gone completely)
// * Please send your feedback, comments, improvement ideas etc. to evmuryshkin@gmail.com
// * Visit https://github.com/EvgenyMuryshkin/QuokkaEvaluation to access latest version of playground
// 
// DISCLAIMER:
//   Code comes AS-IS, it is your responsibility to make sure it is working as expected
//   no responsibility will be taken for any loss or damage caused by use of Quokka toolkit.
// 
// System configuration name is OrGateModule_TopLevel, clock frequency is 1Hz, Top-level
// FSM summary
// -- Packages
module OrGateModule_TopLevel (
// [BEGIN USER PORTS]
// [END USER PORTS]

	input  OrGateModuleI1,
	input  OrGateModuleI2,
	output OrGateModuleO
    );

// [BEGIN USER SIGNALS]
// [END USER SIGNALS]
localparam HiSignal = 1'b1;
localparam LoSignal = 1'b0;
wire  OrGateModule_TopLevel_OrGateModuleI1;
wire  OrGateModule_TopLevel_OrGateModuleI2;
wire  OrGateModule_TopLevel_OrGateModuleO;
wire  OrGateModule_TopLevel_OrGateModule_I1;
wire  OrGateModule_TopLevel_OrGateModule_I2;
wire  OrGateModule_TopLevel_OrGateModule_O;
wire  OrGateModule_TopLevel_OrGateModule_Zero = 1'b0;
wire  OrGateModule_TopLevel_OrGateModule_One = 1'b1;
wire  OrGateModule_TopLevel_OrGateModule_true = 1'b1;
wire  OrGateModule_TopLevel_OrGateModule_false = 1'b0;
wire  OrGateModule_TopLevel_OrGateModule_Inputs_I1;
wire  OrGateModule_TopLevel_OrGateModule_Inputs_I2;
wire  OrGateModule_TopLevel_OrGateModule_SimpleGates_L17F26T48_Expr;
wire  OrGateModule_TopLevel_OrGateModule_SimpleGates_L17F26T48_Expr_1;
wire  OrGateModule_TopLevel_OrGateModule_SimpleGates_L17F26T48_Expr_2;
assign OrGateModule_TopLevel_OrGateModule_SimpleGates_L17F26T48_Expr = OrGateModule_TopLevel_OrGateModule_SimpleGates_L17F26T48_Expr_1 | OrGateModule_TopLevel_OrGateModule_SimpleGates_L17F26T48_Expr_2;
	assign OrGateModule_TopLevel_OrGateModuleI1 = OrGateModuleI1;
	assign OrGateModule_TopLevel_OrGateModuleI2 = OrGateModuleI2;
// Top-level entity connections
assign OrGateModuleO = OrGateModule_TopLevel_OrGateModuleO;
assign OrGateModule_TopLevel_OrGateModule_I1 = OrGateModule_TopLevel_OrGateModuleI1;
assign OrGateModule_TopLevel_OrGateModule_I2 = OrGateModule_TopLevel_OrGateModuleI2;
assign OrGateModule_TopLevel_OrGateModuleO = OrGateModule_TopLevel_OrGateModule_O;
assign OrGateModule_TopLevel_OrGateModule_SimpleGates_L17F26T48_Expr_1 = OrGateModule_TopLevel_OrGateModule_Inputs_I1;
assign OrGateModule_TopLevel_OrGateModule_SimpleGates_L17F26T48_Expr_2 = OrGateModule_TopLevel_OrGateModule_Inputs_I2;
assign OrGateModule_TopLevel_OrGateModule_Inputs_I1 = OrGateModule_TopLevel_OrGateModule_I1;
assign OrGateModule_TopLevel_OrGateModule_Inputs_I2 = OrGateModule_TopLevel_OrGateModule_I2;
assign OrGateModule_TopLevel_OrGateModule_O = OrGateModule_TopLevel_OrGateModule_SimpleGates_L17F26T48_Expr;
// [BEGIN USER ARCHITECTURE]
// [END USER ARCHITECTURE]
endmodule
