// PLEASE READ THIS, IT MAY SAVE YOU SOME TIME AND MONEY, THANK YOU!
// * This file was generated by Quokka FPGA Toolkit.
// * Generated code is your property, do whatever you want with it
// * Place custom code between [BEGIN USER ***] and [END USER ***].
// * CAUTION: All code outside of [USER] scope is subject to regeneration.
// * Bad things happen sometimes in developer's life,
//   it is recommended to use source control management software (e.g. git, bzr etc) to keep your custom code safe'n'sound.
// * Internal structure of code is subject to change.
//   You can use some of signals in custom code, but most likely they will not exist in future (e.g. will get shorter or gone completely)
// * Please send your feedback, comments, improvement ideas etc. to evmuryshkin@gmail.com
// * Visit https://github.com/EvgenyMuryshkin/QuokkaEvaluation to access latest version of playground
// 
// DISCLAIMER:
//   Code comes AS-IS, it is your responsibility to make sure it is working as expected
//   no responsibility will be taken for any loss or damage caused by use of Quokka toolkit.
// 
// System configuration name is InverterModule_TopLevel, clock frequency is 1Hz, Top-level
// FSM summary
// -- Packages
module InverterModule_TopLevel (
// [BEGIN USER PORTS]
// [END USER PORTS]

	input  InverterModuleInput,
	output InverterModuleOutput
    );

// [BEGIN USER SIGNALS]
// [END USER SIGNALS]
localparam HiSignal = 1'b1;
localparam LoSignal = 1'b0;
wire  InverterModule_TopLevel_InverterModuleInput;
wire  InverterModule_TopLevel_InverterModuleOutput;
wire  InverterModule_TopLevel_InverterModule_Input;
wire  InverterModule_TopLevel_InverterModule_Output;
wire  InverterModule_TopLevel_InverterModule_Zero = 1'b0;
wire  InverterModule_TopLevel_InverterModule_One = 1'b1;
wire  InverterModule_TopLevel_InverterModule_true = 1'b1;
wire  InverterModule_TopLevel_InverterModule_false = 1'b0;
wire  InverterModule_TopLevel_InverterModule_Inputs_Input;
wire  InverterModule_TopLevel_InverterModule_InverterModule_L7F31T44_Expr;
wire  InverterModule_TopLevel_InverterModule_InverterModule_L7F31T44_Expr_1;
assign InverterModule_TopLevel_InverterModule_InverterModule_L7F31T44_Expr = ~InverterModule_TopLevel_InverterModule_InverterModule_L7F31T44_Expr_1;
	assign InverterModule_TopLevel_InverterModuleInput = InverterModuleInput;
// Top-level entity connections
assign InverterModuleOutput = InverterModule_TopLevel_InverterModuleOutput;
assign InverterModule_TopLevel_InverterModule_Input = InverterModule_TopLevel_InverterModuleInput;
assign InverterModule_TopLevel_InverterModuleOutput = InverterModule_TopLevel_InverterModule_Output;
assign InverterModule_TopLevel_InverterModule_InverterModule_L7F31T44_Expr_1 = InverterModule_TopLevel_InverterModule_Inputs_Input;
assign InverterModule_TopLevel_InverterModule_Inputs_Input = InverterModule_TopLevel_InverterModule_Input;
assign InverterModule_TopLevel_InverterModule_Output = InverterModule_TopLevel_InverterModule_InverterModule_L7F31T44_Expr;
// [BEGIN USER ARCHITECTURE]
// [END USER ARCHITECTURE]
endmodule
