-- PLEASE READ THIS, IT MAY SAVE YOU SOME TIME AND MONEY, THANK YOU!
-- * This file was generated by Quokka FPGA Toolkit.
-- * Generated code is your property, do whatever you want with it
-- * Place custom code between [BEGIN USER ***] and [END USER ***].
-- * CAUTION: All code outside of [USER] scope is subject to regeneration.
-- * Bad things happen sometimes in developer's life,
--   it is recommended to use source control management software (e.g. git, bzr etc) to keep your custom code safe'n'sound.
-- * Internal structure of code is subject to change.
--   You can use some of signals in custom code, but most likely they will not exist in future (e.g. will get shorter or gone completely)
-- * Please send your feedback, comments, improvement ideas etc. to evmuryshkin@gmail.com
-- * Visit https://github.com/EvgenyMuryshkin/QuokkaEvaluation to access latest version of playground
-- 
-- DISCLAIMER:
--   Code comes AS-IS, it is your responsibility to make sure it is working as expected
--   no responsibility will be taken for any loss or damage caused by use of Quokka toolkit.
-- 
-- System configuration name is AndGateModule_TopLevel, clock frequency is 1Hz, Top-level
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

use work.Quokka.all;

entity AndGateModule_TopLevel is
    port
    (
-- [BEGIN USER PORTS]
-- [END USER PORTS]

AndGateModuleI1 : in  std_logic;
AndGateModuleI2 : in  std_logic;
AndGateModuleO : out  std_logic
    );
end entity;

-- FSM summary
-- Packages
architecture rtl of AndGateModule_TopLevel is
-- [BEGIN USER SIGNALS]
-- [END USER SIGNALS]
constant HiSignal : std_logic := '1';
constant LoSignal : std_logic := '0';
signal AndGateModule_TopLevel_AndGateModuleI1 : std_logic := '0';
signal AndGateModule_TopLevel_AndGateModuleI2 : std_logic := '0';
signal AndGateModule_TopLevel_AndGateModuleO : std_logic := '0';
signal AndGateModule_TopLevel_AndGateModule_I1 : std_logic := '0';
signal AndGateModule_TopLevel_AndGateModule_I2 : std_logic := '0';
signal AndGateModule_TopLevel_AndGateModule_O : std_logic := '0';
constant AndGateModule_TopLevel_AndGateModule_Zero : std_logic := '0';
constant AndGateModule_TopLevel_AndGateModule_One : std_logic := '1';
constant AndGateModule_TopLevel_AndGateModule_true : std_logic := '1';
constant AndGateModule_TopLevel_AndGateModule_false : std_logic := '0';
signal AndGateModule_TopLevel_AndGateModule_Inputs_I1 : std_logic := '0';
signal AndGateModule_TopLevel_AndGateModule_Inputs_I2 : std_logic := '0';
signal AndGateModule_TopLevel_AndGateModule_SimpleGates_L12F26T48_Expr : std_logic := '0';
signal AndGateModule_TopLevel_AndGateModule_SimpleGates_L12F26T48_Expr_1 : std_logic := '0';
signal AndGateModule_TopLevel_AndGateModule_SimpleGates_L12F26T48_Expr_2 : std_logic := '0';
begin

process(AndGateModule_TopLevel_AndGateModule_SimpleGates_L12F26T48_Expr_1, AndGateModule_TopLevel_AndGateModule_SimpleGates_L12F26T48_Expr_2)
begin
AndGateModule_TopLevel_AndGateModule_SimpleGates_L12F26T48_Expr <= AndGateModule_TopLevel_AndGateModule_SimpleGates_L12F26T48_Expr_1 AND AndGateModule_TopLevel_AndGateModule_SimpleGates_L12F26T48_Expr_2;

    end process;
-- Top-level entity connections
process(AndGateModule_TopLevel_AndGateModuleO, AndGateModuleI1, AndGateModuleI2)
begin
	AndGateModule_TopLevel_AndGateModuleI1 <= AndGateModuleI1;
	AndGateModule_TopLevel_AndGateModuleI2 <= AndGateModuleI2;
AndGateModuleO <= AndGateModule_TopLevel_AndGateModuleO;
end process;
process(AndGateModule_TopLevel_AndGateModule_I1, AndGateModule_TopLevel_AndGateModule_I2, AndGateModule_TopLevel_AndGateModule_Inputs_I1, AndGateModule_TopLevel_AndGateModule_Inputs_I2, AndGateModule_TopLevel_AndGateModule_O, AndGateModule_TopLevel_AndGateModule_SimpleGates_L12F26T48_Expr, AndGateModule_TopLevel_AndGateModuleI1, AndGateModule_TopLevel_AndGateModuleI2)
begin
AndGateModule_TopLevel_AndGateModule_I1 <= AndGateModule_TopLevel_AndGateModuleI1;
AndGateModule_TopLevel_AndGateModule_I2 <= AndGateModule_TopLevel_AndGateModuleI2;
AndGateModule_TopLevel_AndGateModuleO <= AndGateModule_TopLevel_AndGateModule_O;
AndGateModule_TopLevel_AndGateModule_SimpleGates_L12F26T48_Expr_1 <= AndGateModule_TopLevel_AndGateModule_Inputs_I1;
AndGateModule_TopLevel_AndGateModule_SimpleGates_L12F26T48_Expr_2 <= AndGateModule_TopLevel_AndGateModule_Inputs_I2;
AndGateModule_TopLevel_AndGateModule_Inputs_I1 <= AndGateModule_TopLevel_AndGateModule_I1;
AndGateModule_TopLevel_AndGateModule_Inputs_I2 <= AndGateModule_TopLevel_AndGateModule_I2;
AndGateModule_TopLevel_AndGateModule_O <= AndGateModule_TopLevel_AndGateModule_SimpleGates_L12F26T48_Expr;
end process;
-- [BEGIN USER ARCHITECTURE]
-- [END USER ARCHITECTURE]
end architecture;
