-- PLEASE READ THIS, IT MAY SAVE YOU SOME TIME AND MONEY, THANK YOU!
-- * This file was generated by Quokka FPGA Toolkit.
-- * Generated code is your property, do whatever you want with it
-- * Place custom code between [BEGIN USER ***] and [END USER ***].
-- * CAUTION: All code outside of [USER] scope is subject to regeneration.
-- * Bad things happen sometimes in developer's life,
--   it is recommended to use source control management software (e.g. git, bzr etc) to keep your custom code safe'n'sound.
-- * Internal structure of code is subject to change.
--   You can use some of signals in custom code, but most likely they will not exist in future (e.g. will get shorter or gone completely)
-- * Please send your feedback, comments, improvement ideas etc. to evmuryshkin@gmail.com
-- * Visit https://github.com/EvgenyMuryshkin/QuokkaEvaluation to access latest version of playground
-- 
-- DISCLAIMER:
--   Code comes AS-IS, it is your responsibility to make sure it is working as expected
--   no responsibility will be taken for any loss or damage caused by use of Quokka toolkit.
-- 
-- System configuration name is SynchronousROMModule_TopLevel, clock frequency is 1Hz, Top-level
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

use work.Quokka.all;

entity SynchronousROMModule_TopLevel is
    port
    (
-- [BEGIN USER PORTS]
-- [END USER PORTS]

Clock : in  std_logic;
Reset : in  std_logic;
Addr1 : in  unsigned(7 downto 0);
Addr2 : in  unsigned(7 downto 0);
Data1 : out  unsigned(7 downto 0);
Data2 : out  unsigned(7 downto 0)
    );
end entity;

-- FSM summary
-- Packages
architecture rtl of SynchronousROMModule_TopLevel is
-- [BEGIN USER SIGNALS]
-- [END USER SIGNALS]
constant HiSignal : std_logic := '1';
constant LoSignal : std_logic := '0';
constant Zero : std_logic := '0';
constant One : std_logic := '1';
constant true : std_logic := '1';
constant false : std_logic := '0';
signal Inputs_Addr1 : unsigned(8 downto 1)  := "00000000";
signal Inputs_Addr2 : unsigned(8 downto 1)  := "00000000";
signal State_Data1 : unsigned(8 downto 1)  := "00000000";
signal State_Data2 : unsigned(8 downto 1)  := "00000000";
type State_BuffArray is array(0 to 255) of unsigned(8 downto 1);
constant State_BuffArrayInit: State_BuffArray:= (
"10110000",
"01001100",
"00100101",
"01001001",
"10001001",
"01000100",
"01001011",
"00111101",
"01100000",
"01110111",
"00101011",
"01111010",
"10010111",
"01001111",
"00010001",
"01111101",
"00100001",
"10001010",
"00011010",
"01010101",
"00110101",
"00111000",
"00101100",
"11101001",
"11101010",
"01001101",
"01000000",
"01000010",
"11001110",
"00010110",
"10000001",
"01100110",
"10000100",
"10101111",
"11011110",
"00101111",
"10000011",
"10100011",
"10110111",
"00000010",
"10101110",
"01101011",
"10011100",
"00000001",
"01010111",
"00110100",
"00011100",
"01101010",
"00101010",
"00010101",
"11011000",
"01100101",
"00000100",
"11101101",
"10111011",
"00001000",
"10110001",
"10010110",
"11111010",
"00100000",
"10011110",
"11001001",
"10010100",
"11100111",
"11100011",
"11011010",
"11101011",
"01101100",
"01111110",
"00111100",
"01111011",
"11001011",
"10011000",
"00001010",
"10001101",
"11000110",
"00110000",
"00001011",
"00001111",
"00000101",
"01111100",
"00111111",
"11101111",
"11001010",
"10010000",
"11000010",
"01110011",
"00110010",
"11101110",
"10011111",
"10010101",
"01011100",
"00100010",
"11111001",
"11101100",
"00001101",
"10000101",
"10000110",
"01100011",
"01101000",
"10111100",
"11000011",
"01111000",
"11100000",
"10101000",
"11110111",
"00111110",
"11110010",
"01010110",
"01010011",
"00001110",
"00101001",
"11111110",
"10100101",
"00010100",
"10110110",
"01011011",
"10110100",
"00111001",
"11001111",
"10000000",
"01011000",
"01000110",
"10100111",
"01100111",
"11110011",
"01010010",
"10101010",
"01000011",
"11010101",
"11110001",
"01001000",
"11011100",
"00001100",
"01101110",
"00000111",
"01000111",
"00110111",
"00011111",
"00010000",
"11100001",
"00000011",
"11000100",
"11100100",
"01011010",
"00100110",
"00011001",
"10111101",
"10101011",
"10010001",
"01110100",
"10100001",
"10100000",
"00010011",
"11100110",
"00100011",
"01011110",
"11011001",
"10110101",
"01101101",
"01111111",
"11111100",
"10100100",
"00110110",
"11111101",
"10111110",
"01010100",
"10010011",
"00101110",
"00111011",
"11011011",
"10010010",
"11001101",
"00110011",
"01110110",
"01001110",
"11110101",
"11001000",
"00000000",
"01110001",
"00011110",
"00010111",
"00111010",
"11011101",
"01100100",
"00011011",
"10100010",
"01110010",
"01000001",
"10110011",
"11100010",
"00000110",
"01011111",
"11000001",
"00101000",
"10000111",
"00001001",
"11110100",
"01110000",
"00110001",
"01101001",
"11010010",
"10011011",
"00101101",
"11100101",
"01011001",
"01000101",
"11000101",
"11010000",
"00100111",
"11011111",
"10101101",
"00010010",
"00011000",
"00100100",
"11000000",
"10001000",
"01001010",
"11001100",
"10001011",
"10001111",
"11111000",
"11010001",
"10100110",
"01100001",
"11110000",
"10011101",
"11000111",
"10111010",
"11010110",
"10001100",
"00011101",
"01011101",
"10111000",
"01010000",
"10001110",
"01010001",
"01111001",
"10011001",
"11101000",
"11111011",
"10110010",
"10111111",
"11010100",
"10101100",
"11010011",
"11111111",
"01100010",
"10101001",
"10111001",
"11010111",
"01101111",
"10011010",
"01110101",
"10000010",
"11110110"
);
signal State_Buff : State_BuffArray := State_BuffArrayInit;
begin
process (Clock, State_Buff)
begin
if rising_edge(Clock) then
State_Data1 <= unsigned(State_Buff(TO_INTEGER(Inputs_Addr1)));
end if;
if rising_edge(Clock) then
State_Data2 <= unsigned(State_Buff(TO_INTEGER(Inputs_Addr2)));
end if;
end process;
process(Addr1, Addr2, State_Data1, State_Data2)
begin
Inputs_Addr1 <= unsigned(Addr1);
Inputs_Addr2 <= unsigned(Addr2);
Data1 <= unsigned(State_Data1);
Data2 <= unsigned(State_Data2);
end process;
-- [BEGIN USER ARCHITECTURE]
-- [END USER ARCHITECTURE]
end architecture;
