-- PLEASE READ THIS, IT MAY SAVE YOU SOME TIME AND MONEY, THANK YOU!
-- * This file was generated by Quokka FPGA Toolkit.
-- * Generated code is your property, do whatever you want with it
-- * Place custom code between [BEGIN USER ***] and [END USER ***].
-- * CAUTION: All code outside of [USER] scope is subject to regeneration.
-- * Bad things happen sometimes in developer's life,
--   it is recommended to use source control management software (e.g. git, bzr etc) to keep your custom code safe'n'sound.
-- * Internal structure of code is subject to change.
--   You can use some of signals in custom code, but most likely they will not exist in future (e.g. will get shorter or gone completely)
-- * Please send your feedback, comments, improvement ideas etc. to evmuryshkin@gmail.com
-- * Visit https://github.com/EvgenyMuryshkin/QuokkaEvaluation to access latest version of playground
-- 
-- DISCLAIMER:
--   Code comes AS-IS, it is your responsibility to make sure it is working as expected
--   no responsibility will be taken for any loss or damage caused by use of Quokka toolkit.
-- 
-- System configuration name is BitArrayModule_TopLevel, clock frequency is 1Hz, Top-level
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

use work.Quokka.all;

entity BitArrayModule_TopLevel is
    port
    (
-- [BEGIN USER PORTS]
-- [END USER PORTS]

BitArrayModuleValue : in  unsigned(8 downto 1);
BitArrayModuleDirect : out  unsigned(8 downto 1);
BitArrayModuleHigh : out  unsigned(4 downto 1);
BitArrayModuleLow : out  unsigned(4 downto 1);
BitArrayModuleReversed : out  unsigned(8 downto 1);
BitArrayModuleReversedHigh : out  unsigned(4 downto 1);
BitArrayModuleReversedLow : out  unsigned(4 downto 1);
BitArrayModulePicks : out  unsigned(4 downto 1)
    );
end entity;

-- FSM summary
-- Packages
architecture rtl of BitArrayModule_TopLevel is
-- [BEGIN USER SIGNALS]
-- [END USER SIGNALS]
constant HiSignal : std_logic := '1';
constant LoSignal : std_logic := '0';
signal BitArrayModule_TopLevel_BitArrayModuleValue : unsigned(8 downto 1) := (others => '0');
signal BitArrayModule_TopLevel_BitArrayModuleDirect : unsigned(8 downto 1) := (others => '0');
signal BitArrayModule_TopLevel_BitArrayModuleHigh : unsigned(4 downto 1) := (others => '0');
signal BitArrayModule_TopLevel_BitArrayModuleLow : unsigned(4 downto 1) := (others => '0');
signal BitArrayModule_TopLevel_BitArrayModuleReversed : unsigned(8 downto 1) := (others => '0');
signal BitArrayModule_TopLevel_BitArrayModuleReversedHigh : unsigned(4 downto 1) := (others => '0');
signal BitArrayModule_TopLevel_BitArrayModuleReversedLow : unsigned(4 downto 1) := (others => '0');
signal BitArrayModule_TopLevel_BitArrayModulePicks : unsigned(4 downto 1) := (others => '0');
signal BitArrayModule_TopLevel_BitArrayModule_Value : unsigned(8 downto 1) := (others => '0');
signal BitArrayModule_TopLevel_BitArrayModule_Direct : unsigned(8 downto 1) := (others => '0');
signal BitArrayModule_TopLevel_BitArrayModule_High : unsigned(4 downto 1) := (others => '0');
signal BitArrayModule_TopLevel_BitArrayModule_Low : unsigned(4 downto 1) := (others => '0');
signal BitArrayModule_TopLevel_BitArrayModule_Reversed : unsigned(8 downto 1) := (others => '0');
signal BitArrayModule_TopLevel_BitArrayModule_ReversedHigh : unsigned(4 downto 1) := (others => '0');
signal BitArrayModule_TopLevel_BitArrayModule_ReversedLow : unsigned(4 downto 1) := (others => '0');
signal BitArrayModule_TopLevel_BitArrayModule_Picks : unsigned(4 downto 1) := (others => '0');
constant BitArrayModule_TopLevel_BitArrayModule_Zero : std_logic := '0';
constant BitArrayModule_TopLevel_BitArrayModule_One : std_logic := '1';
constant BitArrayModule_TopLevel_BitArrayModule_true : std_logic := '1';
constant BitArrayModule_TopLevel_BitArrayModule_false : std_logic := '0';
signal BitArrayModule_TopLevel_BitArrayModule_Inputs_Value : unsigned(8 downto 1)  := "00000000";
signal BitArrayModule_TopLevel_BitArrayModule_Bits : unsigned(8 downto 1)  := "00000000";
signal BitArrayModule_TopLevel_BitArrayModule_BitArrayModule_L15F36T46_Index : unsigned(4 downto 1)  := "0000";
signal BitArrayModule_TopLevel_BitArrayModule_BitArrayModule_L16F35T45_Index : unsigned(4 downto 1)  := "0000";
signal BitArrayModule_TopLevel_BitArrayModule_BitArrayModule_L17F40T50_Index : unsigned(8 downto 1)  := "00000000";
signal BitArrayModule_TopLevel_BitArrayModule_BitArrayModule_L18F44T54_Index : unsigned(4 downto 1)  := "0000";
signal BitArrayModule_TopLevel_BitArrayModule_BitArrayModule_L19F43T53_Index : unsigned(4 downto 1)  := "0000";
signal BitArrayModule_TopLevel_BitArrayModule_BitArrayModule_L20F37T74_Source : unsigned(4 downto 1)  := "0000";
signal BitArrayModule_TopLevel_BitArrayModule_BitArrayModule_L20F53T62_Index : unsigned(2 downto 1)  := "00";
signal BitArrayModule_TopLevel_BitArrayModule_BitArrayModule_L20F64T73_Index : unsigned(2 downto 1)  := "00";
begin
-- Top-level entity connections
process(BitArrayModule_TopLevel_BitArrayModuleDirect, BitArrayModule_TopLevel_BitArrayModuleHigh, BitArrayModule_TopLevel_BitArrayModuleLow, BitArrayModule_TopLevel_BitArrayModulePicks, BitArrayModule_TopLevel_BitArrayModuleReversed, BitArrayModule_TopLevel_BitArrayModuleReversedHigh, BitArrayModule_TopLevel_BitArrayModuleReversedLow, BitArrayModuleValue)
begin
	BitArrayModule_TopLevel_BitArrayModuleValue <= BitArrayModuleValue;
BitArrayModuleDirect <= BitArrayModule_TopLevel_BitArrayModuleDirect;
BitArrayModuleHigh <= BitArrayModule_TopLevel_BitArrayModuleHigh;
BitArrayModuleLow <= BitArrayModule_TopLevel_BitArrayModuleLow;
BitArrayModuleReversed <= BitArrayModule_TopLevel_BitArrayModuleReversed;
BitArrayModuleReversedHigh <= BitArrayModule_TopLevel_BitArrayModuleReversedHigh;
BitArrayModuleReversedLow <= BitArrayModule_TopLevel_BitArrayModuleReversedLow;
BitArrayModulePicks <= BitArrayModule_TopLevel_BitArrayModulePicks;
end process;
process(BitArrayModule_TopLevel_BitArrayModule_BitArrayModule_L15F36T46_Index, BitArrayModule_TopLevel_BitArrayModule_BitArrayModule_L16F35T45_Index, BitArrayModule_TopLevel_BitArrayModule_BitArrayModule_L17F40T50_Index, BitArrayModule_TopLevel_BitArrayModule_BitArrayModule_L18F44T54_Index, BitArrayModule_TopLevel_BitArrayModule_BitArrayModule_L19F43T53_Index, BitArrayModule_TopLevel_BitArrayModule_BitArrayModule_L20F37T74_Source, BitArrayModule_TopLevel_BitArrayModule_BitArrayModule_L20F53T62_Index, BitArrayModule_TopLevel_BitArrayModule_BitArrayModule_L20F64T73_Index, BitArrayModule_TopLevel_BitArrayModule_Bits, BitArrayModule_TopLevel_BitArrayModule_Direct, BitArrayModule_TopLevel_BitArrayModule_High, BitArrayModule_TopLevel_BitArrayModule_Inputs_Value, BitArrayModule_TopLevel_BitArrayModule_Low, BitArrayModule_TopLevel_BitArrayModule_Picks, BitArrayModule_TopLevel_BitArrayModule_Reversed, BitArrayModule_TopLevel_BitArrayModule_ReversedHigh, BitArrayModule_TopLevel_BitArrayModule_ReversedLow, BitArrayModule_TopLevel_BitArrayModule_Value, BitArrayModule_TopLevel_BitArrayModuleValue)
begin
BitArrayModule_TopLevel_BitArrayModule_Value <= BitArrayModule_TopLevel_BitArrayModuleValue;
BitArrayModule_TopLevel_BitArrayModuleDirect <= BitArrayModule_TopLevel_BitArrayModule_Direct;
BitArrayModule_TopLevel_BitArrayModuleHigh <= BitArrayModule_TopLevel_BitArrayModule_High;
BitArrayModule_TopLevel_BitArrayModuleLow <= BitArrayModule_TopLevel_BitArrayModule_Low;
BitArrayModule_TopLevel_BitArrayModuleReversed <= BitArrayModule_TopLevel_BitArrayModule_Reversed;
BitArrayModule_TopLevel_BitArrayModuleReversedHigh <= BitArrayModule_TopLevel_BitArrayModule_ReversedHigh;
BitArrayModule_TopLevel_BitArrayModuleReversedLow <= BitArrayModule_TopLevel_BitArrayModule_ReversedLow;
BitArrayModule_TopLevel_BitArrayModulePicks <= BitArrayModule_TopLevel_BitArrayModule_Picks;
BitArrayModule_TopLevel_BitArrayModule_Inputs_Value <= unsigned(BitArrayModule_TopLevel_BitArrayModule_Value);
BitArrayModule_TopLevel_BitArrayModule_Bits <= unsigned(BitArrayModule_TopLevel_BitArrayModule_Inputs_Value);
BitArrayModule_TopLevel_BitArrayModule_Direct <= unsigned(BitArrayModule_TopLevel_BitArrayModule_Bits);
BitArrayModule_TopLevel_BitArrayModule_BitArrayModule_L15F36T46_Index <= unsigned(BitArrayModule_TopLevel_BitArrayModule_Bits(8 downto 5));
BitArrayModule_TopLevel_BitArrayModule_High <= unsigned(BitArrayModule_TopLevel_BitArrayModule_BitArrayModule_L15F36T46_Index);
BitArrayModule_TopLevel_BitArrayModule_BitArrayModule_L16F35T45_Index <= unsigned(BitArrayModule_TopLevel_BitArrayModule_Bits(4 downto 1));
BitArrayModule_TopLevel_BitArrayModule_Low <= unsigned(BitArrayModule_TopLevel_BitArrayModule_BitArrayModule_L16F35T45_Index);
BitArrayModule_TopLevel_BitArrayModule_BitArrayModule_L17F40T50_Index <= (1 => BitArrayModule_TopLevel_BitArrayModule_Bits(8), 2 => BitArrayModule_TopLevel_BitArrayModule_Bits(7), 3 => BitArrayModule_TopLevel_BitArrayModule_Bits(6), 4 => BitArrayModule_TopLevel_BitArrayModule_Bits(5), 5 => BitArrayModule_TopLevel_BitArrayModule_Bits(4), 6 => BitArrayModule_TopLevel_BitArrayModule_Bits(3), 7 => BitArrayModule_TopLevel_BitArrayModule_Bits(2), 8 => BitArrayModule_TopLevel_BitArrayModule_Bits(1), others => '0');
BitArrayModule_TopLevel_BitArrayModule_Reversed <= unsigned(BitArrayModule_TopLevel_BitArrayModule_BitArrayModule_L17F40T50_Index);
BitArrayModule_TopLevel_BitArrayModule_BitArrayModule_L18F44T54_Index <= (1 => BitArrayModule_TopLevel_BitArrayModule_Bits(8), 2 => BitArrayModule_TopLevel_BitArrayModule_Bits(7), 3 => BitArrayModule_TopLevel_BitArrayModule_Bits(6), 4 => BitArrayModule_TopLevel_BitArrayModule_Bits(5), others => '0');
BitArrayModule_TopLevel_BitArrayModule_ReversedHigh <= unsigned(BitArrayModule_TopLevel_BitArrayModule_BitArrayModule_L18F44T54_Index);
BitArrayModule_TopLevel_BitArrayModule_BitArrayModule_L19F43T53_Index <= (1 => BitArrayModule_TopLevel_BitArrayModule_Bits(4), 2 => BitArrayModule_TopLevel_BitArrayModule_Bits(3), 3 => BitArrayModule_TopLevel_BitArrayModule_Bits(2), 4 => BitArrayModule_TopLevel_BitArrayModule_Bits(1), others => '0');
BitArrayModule_TopLevel_BitArrayModule_ReversedLow <= unsigned(BitArrayModule_TopLevel_BitArrayModule_BitArrayModule_L19F43T53_Index);
BitArrayModule_TopLevel_BitArrayModule_BitArrayModule_L20F53T62_Index <= unsigned(BitArrayModule_TopLevel_BitArrayModule_Bits(7 downto 6));
BitArrayModule_TopLevel_BitArrayModule_BitArrayModule_L20F64T73_Index <= (1 => BitArrayModule_TopLevel_BitArrayModule_Bits(3), 2 => BitArrayModule_TopLevel_BitArrayModule_Bits(2), others => '0');
BitArrayModule_TopLevel_BitArrayModule_BitArrayModule_L20F37T74_Source <= (1 => BitArrayModule_TopLevel_BitArrayModule_BitArrayModule_L20F53T62_Index(1), 2 => BitArrayModule_TopLevel_BitArrayModule_BitArrayModule_L20F53T62_Index(2), 3 => BitArrayModule_TopLevel_BitArrayModule_BitArrayModule_L20F64T73_Index(1), 4 => BitArrayModule_TopLevel_BitArrayModule_BitArrayModule_L20F64T73_Index(2), others => '0');
BitArrayModule_TopLevel_BitArrayModule_Picks <= unsigned(BitArrayModule_TopLevel_BitArrayModule_BitArrayModule_L20F37T74_Source);
end process;
-- [BEGIN USER ARCHITECTURE]
-- [END USER ARCHITECTURE]
end architecture;
