-- PLEASE READ THIS, IT MAY SAVE YOU SOME TIME AND MONEY, THANK YOU!
-- * This file was generated by Quokka FPGA Toolkit.
-- * Generated code is your property, do whatever you want with it
-- * Place custom code between [BEGIN USER ***] and [END USER ***].
-- * CAUTION: All code outside of [USER] scope is subject to regeneration.
-- * Bad things happen sometimes in developer's life,
--   it is recommended to use source control management software (e.g. git, bzr etc) to keep your custom code safe'n'sound.
-- * Internal structure of code is subject to change.
--   You can use some of signals in custom code, but most likely they will not exist in future (e.g. will get shorter or gone completely)
-- * Please send your feedback, comments, improvement ideas etc. to evmuryshkin@gmail.com
-- * Visit https://github.com/EvgenyMuryshkin/QuokkaEvaluation to access latest version of playground
-- 
-- DISCLAIMER:
--   Code comes AS-IS, it is your responsibility to make sure it is working as expected
--   no responsibility will be taken for any loss or damage caused by use of Quokka toolkit.
-- 
-- System configuration name is SynchronousRAMModule_TopLevel, clock frequency is 1Hz, Top-level
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

use work.Quokka.all;

entity SynchronousRAMModule_TopLevel is
    port
    (
-- [BEGIN USER PORTS]
-- [END USER PORTS]

Clock : in  std_logic;
Reset : in  std_logic;
Value : in  unsigned(7 downto 0);
Avg : out  unsigned(7 downto 0)
    );
end entity;

-- FSM summary
-- Packages
architecture rtl of SynchronousRAMModule_TopLevel is
-- [BEGIN USER SIGNALS]
-- [END USER SIGNALS]
constant HiSignal : std_logic := '1';
constant LoSignal : std_logic := '0';
constant Zero : std_logic := '0';
constant One : std_logic := '1';
constant true : std_logic := '1';
constant false : std_logic := '0';
constant SynchronousRAMModule_L28F9L31T10_SynchronousRAMModule_L30F52T53_Expr : std_logic := '1';
constant SynchronousRAMModule_L25F47T48_Expr : std_logic := '0';
constant SynchronousRAMModule_L25F63T64_Expr : std_logic := '1';
constant SynchronousRAMModule_L25F79T80_Expr : unsigned(2 downto 1)  := "10";
constant SynchronousRAMModule_L25F95T96_Expr : unsigned(2 downto 1)  := "11";
constant SynchronousRAMModule_L25F102T103_Expr : unsigned(2 downto 1)  := "10";
signal Inputs_Value : unsigned(8 downto 1)  := "00000000";
signal NextState_Index : unsigned(8 downto 1)  := "00000000";
signal SynchronousRAMModule_L28F9L31T10_SynchronousRAMModule_L30F31T54_Expr : unsigned(8 downto 1)  := "00000000";
signal SynchronousRAMModule_L25F36T49_Index : unsigned(8 downto 1)  := "00000000";
signal SynchronousRAMModule_L25F52T65_Index : unsigned(8 downto 1)  := "00000000";
signal SynchronousRAMModule_L25F68T81_Index : unsigned(8 downto 1)  := "00000000";
signal SynchronousRAMModule_L25F84T97_Index : unsigned(8 downto 1)  := "00000000";
signal SynchronousRAMModule_L25F28T104_Expr : unsigned(8 downto 1)  := "00000000";
signal State_Index : unsigned(8 downto 1)  := "00000000";
constant State_IndexDefault : unsigned(8 downto 1)  := "00000000";
signal SynchronousRAMModule_L25F35T103_Expr : unsigned(11 downto 1)  := "00000000000";
signal SynchronousRAMModule_L25F35T103_Expr_1 : unsigned(11 downto 1)  := "00000000000";
signal SynchronousRAMModule_L28F9L31T10_SynchronousRAMModule_L30F38T53_Expr : unsigned(10 downto 1)  := "0000000000";
signal SynchronousRAMModule_L28F9L31T10_SynchronousRAMModule_L30F38T53_Expr_1 : signed(10 downto 1)  := "0000000000";
signal SynchronousRAMModule_L28F9L31T10_SynchronousRAMModule_L30F38T53_Expr_2 : signed(10 downto 1)  := "0000000000";
signal SynchronousRAMModule_L25F36T97_Expr : unsigned(14 downto 1)  := "00000000000000";
signal SynchronousRAMModule_L25F36T97_Expr_1 : signed(14 downto 1)  := "00000000000000";
signal SynchronousRAMModule_L25F36T97_Expr_2 : signed(14 downto 1)  := "00000000000000";
signal SynchronousRAMModule_L25F36T81_Expr : unsigned(12 downto 1)  := "000000000000";
signal SynchronousRAMModule_L25F36T81_Expr_1 : signed(12 downto 1)  := "000000000000";
signal SynchronousRAMModule_L25F36T81_Expr_2 : signed(12 downto 1)  := "000000000000";
signal SynchronousRAMModule_L25F36T65_Expr : unsigned(10 downto 1)  := "0000000000";
signal SynchronousRAMModule_L25F36T65_Expr_1 : signed(10 downto 1)  := "0000000000";
signal SynchronousRAMModule_L25F36T65_Expr_2 : signed(10 downto 1)  := "0000000000";
type State_BuffArray is array(0 to 3) of unsigned(8 downto 1);
constant State_BuffArrayInit: State_BuffArray:= (
"00000000",
"00000000",
"00000000",
"00000000"
);
signal State_Buff : State_BuffArray := State_BuffArrayInit;
type NextState_BuffArray is array(0 to 3) of unsigned(8 downto 1);
constant NextState_BuffArrayInit: NextState_BuffArray:= (
"00000000",
"00000000",
"00000000",
"00000000"
);
signal NextState_Buff : NextState_BuffArray := NextState_BuffArrayInit;
begin
process (Clock, NextState_Index, Reset)
begin
if rising_edge(Clock) then
if ( Reset = '1' ) then
State_Index <= State_IndexDefault;
else
State_Index <= NextState_Index;
end if;
end if;
end process;
process(SynchronousRAMModule_L25F35T103_Expr_1)
alias output is SynchronousRAMModule_L25F35T103_Expr;
alias source0 is SynchronousRAMModule_L25F35T103_Expr_1;
begin
-- Output: SynchronousRAMModule_L25F35T103_Expr, Width: 11, ShiftBy: 2, Sources: 1
output(1) <= source0(3);
output(2) <= source0(4);
output(3) <= source0(5);
output(4) <= source0(6);
output(5) <= source0(7);
output(6) <= source0(8);
output(7) <= source0(9);
output(8) <= source0(10);
output(9) <= source0(11);
output(10) <= '0';
output(11) <= '0';
end process;

process(SynchronousRAMModule_L28F9L31T10_SynchronousRAMModule_L30F38T53_Expr_1, SynchronousRAMModule_L28F9L31T10_SynchronousRAMModule_L30F38T53_Expr_2)
begin
    SynchronousRAMModule_L28F9L31T10_SynchronousRAMModule_L30F38T53_Expr <= resize(unsigned(signed(resize(SynchronousRAMModule_L28F9L31T10_SynchronousRAMModule_L30F38T53_Expr_1, SynchronousRAMModule_L28F9L31T10_SynchronousRAMModule_L30F38T53_Expr_1'length + 1)) + signed(resize(SynchronousRAMModule_L28F9L31T10_SynchronousRAMModule_L30F38T53_Expr_2, SynchronousRAMModule_L28F9L31T10_SynchronousRAMModule_L30F38T53_Expr_2'length + 1))), SynchronousRAMModule_L28F9L31T10_SynchronousRAMModule_L30F38T53_Expr'length);

end process;

process(SynchronousRAMModule_L25F36T97_Expr_1, SynchronousRAMModule_L25F36T97_Expr_2)
begin
    SynchronousRAMModule_L25F36T97_Expr <= resize(unsigned(signed(resize(SynchronousRAMModule_L25F36T97_Expr_1, SynchronousRAMModule_L25F36T97_Expr_1'length + 1)) + signed(resize(SynchronousRAMModule_L25F36T97_Expr_2, SynchronousRAMModule_L25F36T97_Expr_2'length + 1))), SynchronousRAMModule_L25F36T97_Expr'length);

end process;

process(SynchronousRAMModule_L25F36T81_Expr_1, SynchronousRAMModule_L25F36T81_Expr_2)
begin
    SynchronousRAMModule_L25F36T81_Expr <= resize(unsigned(signed(resize(SynchronousRAMModule_L25F36T81_Expr_1, SynchronousRAMModule_L25F36T81_Expr_1'length + 1)) + signed(resize(SynchronousRAMModule_L25F36T81_Expr_2, SynchronousRAMModule_L25F36T81_Expr_2'length + 1))), SynchronousRAMModule_L25F36T81_Expr'length);

end process;

process(SynchronousRAMModule_L25F36T65_Expr_1, SynchronousRAMModule_L25F36T65_Expr_2)
begin
    SynchronousRAMModule_L25F36T65_Expr <= resize(unsigned(signed(resize(SynchronousRAMModule_L25F36T65_Expr_1, SynchronousRAMModule_L25F36T65_Expr_1'length + 1)) + signed(resize(SynchronousRAMModule_L25F36T65_Expr_2, SynchronousRAMModule_L25F36T65_Expr_2'length + 1))), SynchronousRAMModule_L25F36T65_Expr'length);

end process;
process (Clock, Inputs_Value)
begin
if rising_edge(Clock) then
NextState_Buff <= unsigned(Inputs_Value);
end if;
end process;
process(State_Index, SynchronousRAMModule_L28F9L31T10_SynchronousRAMModule_L30F31T54_Expr)
begin
NextState_Index <= unsigned(State_Index);
NextState_Index <= unsigned(SynchronousRAMModule_L28F9L31T10_SynchronousRAMModule_L30F31T54_Expr);
end process;
-- Top-level entity connections
process(Clock, Reset, SynchronousRAMModule_TopLevel_Avg, Value)
begin
	SynchronousRAMModule_TopLevel_Value <= Value;
SynchronousRAMModule_TopLevel_Clock <= Clock;
SynchronousRAMModule_TopLevel_Reset <= NOT Reset;
Avg <= SynchronousRAMModule_TopLevel_Avg;
end process;
process(State_Buff, State_Index, SynchronousRAMModule_L25F28T104_Expr, SynchronousRAMModule_L25F35T103_Expr, SynchronousRAMModule_L25F36T49_Index, SynchronousRAMModule_L25F36T65_Expr, SynchronousRAMModule_L25F36T81_Expr, SynchronousRAMModule_L25F36T97_Expr, SynchronousRAMModule_L25F52T65_Index, SynchronousRAMModule_L25F68T81_Index, SynchronousRAMModule_L25F84T97_Index, SynchronousRAMModule_L28F9L31T10_SynchronousRAMModule_L30F38T53_Expr, Value)
begin
SynchronousRAMModule_L25F36T49_Index <= State_Buff(TO_INTEGER(UNSIGNED(SynchronousRAMModule_L25F47T48_Expr)));
SynchronousRAMModule_L25F52T65_Index <= State_Buff(TO_INTEGER(UNSIGNED(SynchronousRAMModule_L25F63T64_Expr)));
SynchronousRAMModule_L25F68T81_Index <= State_Buff(TO_INTEGER(UNSIGNED(SynchronousRAMModule_L25F79T80_Expr)));
SynchronousRAMModule_L25F84T97_Index <= State_Buff(TO_INTEGER(UNSIGNED(SynchronousRAMModule_L25F95T96_Expr)));
SynchronousRAMModule_L25F35T103_Expr_1 <= unsigned(SynchronousRAMModule_L25F36T97_Expr(11 downto 1));
SynchronousRAMModule_L28F9L31T10_SynchronousRAMModule_L30F38T53_Expr_1 <= signed(resize(State_Index, SynchronousRAMModule_L28F9L31T10_SynchronousRAMModule_L30F38T53_Expr_1'length));
SynchronousRAMModule_L28F9L31T10_SynchronousRAMModule_L30F38T53_Expr_2 <= (1 => SynchronousRAMModule_L28F9L31T10_SynchronousRAMModule_L30F52T53_Expr, others => '0');
SynchronousRAMModule_L25F36T97_Expr_1 <= signed(resize(SynchronousRAMModule_L25F36T81_Expr, SynchronousRAMModule_L25F36T97_Expr_1'length));
SynchronousRAMModule_L25F36T97_Expr_2 <= signed(resize(SynchronousRAMModule_L25F84T97_Index, SynchronousRAMModule_L25F36T97_Expr_2'length));
SynchronousRAMModule_L25F36T81_Expr_1 <= signed(resize(SynchronousRAMModule_L25F36T65_Expr, SynchronousRAMModule_L25F36T81_Expr_1'length));
SynchronousRAMModule_L25F36T81_Expr_2 <= signed(resize(SynchronousRAMModule_L25F68T81_Index, SynchronousRAMModule_L25F36T81_Expr_2'length));
SynchronousRAMModule_L25F36T65_Expr_1 <= signed(resize(SynchronousRAMModule_L25F36T49_Index, SynchronousRAMModule_L25F36T65_Expr_1'length));
SynchronousRAMModule_L25F36T65_Expr_2 <= signed(resize(SynchronousRAMModule_L25F52T65_Index, SynchronousRAMModule_L25F36T65_Expr_2'length));
Inputs_Value <= unsigned(Value);
SynchronousRAMModule_L28F9L31T10_SynchronousRAMModule_L30F31T54_Expr <= unsigned(SynchronousRAMModule_L28F9L31T10_SynchronousRAMModule_L30F38T53_Expr(8 downto 1));
SynchronousRAMModule_L25F28T104_Expr <= unsigned(SynchronousRAMModule_L25F35T103_Expr(8 downto 1));
Avg <= unsigned(SynchronousRAMModule_L25F28T104_Expr);
end process;
-- [BEGIN USER ARCHITECTURE]
-- [END USER ARCHITECTURE]
end architecture;
