// partial declaration for MemBlock SoC. Generated by QuokkaAssembly
using QuSoC;
namespace MemBlock
{
	public partial class MemBlock
	{
		internal SoCRegisterModule CounterModule;
		internal SoCBlockRAMModule MemBlockModule;
		protected override ISoCComponentModule[] GeneratedModules => new ISoCComponentModule[] { CounterModule,MemBlockModule };
		protected override void CreateGeneratedModules()
		{
			CounterModule = new SoCRegisterModule();
			MemBlockModule = new SoCBlockRAMModule(1024);
		} // CreateGeneratedModules
		protected override void ScheduleGeneratedModules()
		{
			CounterModule.Schedule(() => new SoCRegisterModuleInputs() { Common = ModuleCommon, DeviceAddress = 0x80000000 });
			MemBlockModule.Schedule(() => new SoCBlockRAMModuleInputs() { Common = ModuleCommon, DeviceAddress = 0x80100000 });
		} // ScheduleGeneratedModules
	}
}
