// PLEASE READ THIS, IT MAY SAVE YOU SOME TIME AND MONEY, THANK YOU!
// * This file was generated by Quokka FPGA Toolkit.
// * Generated code is your property, do whatever you want with it
// * Place custom code between [BEGIN USER ***] and [END USER ***].
// * CAUTION: All code outside of [USER] scope is subject to regeneration.
// * Bad things happen sometimes in developer's life,
//   it is recommended to use source control management software (e.g. git, bzr etc) to keep your custom code safe'n'sound.
// * Internal structure of code is subject to change.
//   You can use some of signals in custom code, but most likely they will not exist in future (e.g. will get shorter or gone completely)
// * Please send your feedback, comments, improvement ideas etc. to evmuryshkin@gmail.com
// * Visit https://github.com/EvgenyMuryshkin/QuokkaEvaluation to access latest version of playground
// 
// DISCLAIMER:
//   Code comes AS-IS, it is your responsibility to make sure it is working as expected
//   no responsibility will be taken for any loss or damage caused by use of Quokka toolkit.
// 
// System configuration name is XorGateModule_TopLevel, clock frequency is 1Hz, Top-level
// FSM summary
// -- Packages
module XorGateModule_TopLevel (
// [BEGIN USER PORTS]
// [END USER PORTS]

	input  XorGateModuleI1,
	input  XorGateModuleI2,
	output XorGateModuleO
    );

// [BEGIN USER SIGNALS]
// [END USER SIGNALS]
localparam HiSignal = 1'b1;
localparam LoSignal = 1'b0;
wire  XorGateModule_TopLevel_XorGateModuleI1;
wire  XorGateModule_TopLevel_XorGateModuleI2;
wire  XorGateModule_TopLevel_XorGateModuleO;
wire  XorGateModule_TopLevel_XorGateModule_I1;
wire  XorGateModule_TopLevel_XorGateModule_I2;
wire  XorGateModule_TopLevel_XorGateModule_O;
wire  XorGateModule_TopLevel_XorGateModule_Zero = 1'b0;
wire  XorGateModule_TopLevel_XorGateModule_One = 1'b1;
wire  XorGateModule_TopLevel_XorGateModule_true = 1'b1;
wire  XorGateModule_TopLevel_XorGateModule_false = 1'b0;
wire  XorGateModule_TopLevel_XorGateModule_Inputs_I1;
wire  XorGateModule_TopLevel_XorGateModule_Inputs_I2;
wire  XorGateModule_TopLevel_XorGateModule_SimpleGates_L22F26T47_Expr;
wire  XorGateModule_TopLevel_XorGateModule_SimpleGates_L22F26T47_Expr_1;
wire  XorGateModule_TopLevel_XorGateModule_SimpleGates_L22F26T47_Expr_2;
assign XorGateModule_TopLevel_XorGateModule_SimpleGates_L22F26T47_Expr = XorGateModule_TopLevel_XorGateModule_SimpleGates_L22F26T47_Expr_1 ^ XorGateModule_TopLevel_XorGateModule_SimpleGates_L22F26T47_Expr_2;
	assign XorGateModule_TopLevel_XorGateModuleI1 = XorGateModuleI1;
	assign XorGateModule_TopLevel_XorGateModuleI2 = XorGateModuleI2;
// Top-level entity connections
assign XorGateModuleO = XorGateModule_TopLevel_XorGateModuleO;
assign XorGateModule_TopLevel_XorGateModule_I1 = XorGateModule_TopLevel_XorGateModuleI1;
assign XorGateModule_TopLevel_XorGateModule_I2 = XorGateModule_TopLevel_XorGateModuleI2;
assign XorGateModule_TopLevel_XorGateModuleO = XorGateModule_TopLevel_XorGateModule_O;
assign XorGateModule_TopLevel_XorGateModule_SimpleGates_L22F26T47_Expr_1 = XorGateModule_TopLevel_XorGateModule_Inputs_I1;
assign XorGateModule_TopLevel_XorGateModule_SimpleGates_L22F26T47_Expr_2 = XorGateModule_TopLevel_XorGateModule_Inputs_I2;
assign XorGateModule_TopLevel_XorGateModule_Inputs_I1 = XorGateModule_TopLevel_XorGateModule_I1;
assign XorGateModule_TopLevel_XorGateModule_Inputs_I2 = XorGateModule_TopLevel_XorGateModule_I2;
assign XorGateModule_TopLevel_XorGateModule_O = XorGateModule_TopLevel_XorGateModule_SimpleGates_L22F26T47_Expr;
// [BEGIN USER ARCHITECTURE]
// [END USER ARCHITECTURE]
endmodule
