-- PLEASE READ THIS, IT MAY SAVE YOU SOME TIME AND MONEY, THANK YOU!
-- * This file was generated by Quokka FPGA Toolkit.
-- * Generated code is your property, do whatever you want with it
-- * Place custom code between [BEGIN USER ***] and [END USER ***].
-- * CAUTION: All code outside of [USER] scope is subject to regeneration.
-- * Bad things happen sometimes in developer's life,
--   it is recommended to use source control management software (e.g. git, bzr etc) to keep your custom code safe'n'sound.
-- * Internal structure of code is subject to change.
--   You can use some of signals in custom code, but most likely they will not exist in future (e.g. will get shorter or gone completely)
-- * Please send your feedback, comments, improvement ideas etc. to evmuryshkin@gmail.com
-- * Visit https://github.com/EvgenyMuryshkin/QuokkaEvaluation to access latest version of playground
-- 
-- DISCLAIMER:
--   Code comes AS-IS, it is your responsibility to make sure it is working as expected
--   no responsibility will be taken for any loss or damage caused by use of Quokka toolkit.
-- 
-- System configuration name is FullAdderModule_TopLevel, clock frequency is 1Hz, Top-level
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

use work.Quokka.all;

entity FullAdderModule_TopLevel is
    port
    (
-- [BEGIN USER PORTS]
-- [END USER PORTS]

FullAdderModuleA : in  std_logic;
FullAdderModuleB : in  std_logic;
FullAdderModuleCIn : in  std_logic;
FullAdderModuleO : out  std_logic;
FullAdderModuleCOut : out  std_logic
    );
end entity;

-- FSM summary
-- Packages
architecture rtl of FullAdderModule_TopLevel is
-- [BEGIN USER SIGNALS]
-- [END USER SIGNALS]
constant HiSignal : std_logic := '1';
constant LoSignal : std_logic := '0';
signal FullAdderModule_TopLevel_FullAdderModuleA : std_logic := '0';
signal FullAdderModule_TopLevel_FullAdderModuleB : std_logic := '0';
signal FullAdderModule_TopLevel_FullAdderModuleCIn : std_logic := '0';
signal FullAdderModule_TopLevel_FullAdderModuleO : std_logic := '0';
signal FullAdderModule_TopLevel_FullAdderModuleCOut : std_logic := '0';
signal FullAdderModule_TopLevel_FullAdderModule_A : std_logic := '0';
signal FullAdderModule_TopLevel_FullAdderModule_B : std_logic := '0';
signal FullAdderModule_TopLevel_FullAdderModule_CIn : std_logic := '0';
signal FullAdderModule_TopLevel_FullAdderModule_O : std_logic := '0';
signal FullAdderModule_TopLevel_FullAdderModule_COut : std_logic := '0';
constant FullAdderModule_TopLevel_FullAdderModule_Zero : std_logic := '0';
constant FullAdderModule_TopLevel_FullAdderModule_One : std_logic := '1';
constant FullAdderModule_TopLevel_FullAdderModule_true : std_logic := '1';
constant FullAdderModule_TopLevel_FullAdderModule_false : std_logic := '0';
signal FullAdderModule_TopLevel_FullAdderModule_Inputs_A : std_logic := '0';
signal FullAdderModule_TopLevel_FullAdderModule_Inputs_B : std_logic := '0';
signal FullAdderModule_TopLevel_FullAdderModule_Inputs_CIn : std_logic := '0';
signal FullAdderModule_TopLevel_FullAdderModule_P : std_logic := '0';
signal FullAdderModule_TopLevel_FullAdderModule_FullAdder_L14F27T46_Expr : std_logic := '0';
signal FullAdderModule_TopLevel_FullAdderModule_FullAdder_L14F27T46_Expr_1 : std_logic := '0';
signal FullAdderModule_TopLevel_FullAdderModule_FullAdder_L14F27T46_Expr_2 : std_logic := '0';
signal FullAdderModule_TopLevel_FullAdderModule_FullAdder_L16F26T40_Expr : std_logic := '0';
signal FullAdderModule_TopLevel_FullAdderModule_FullAdder_L16F26T40_Expr_1 : std_logic := '0';
signal FullAdderModule_TopLevel_FullAdderModule_FullAdder_L16F26T40_Expr_2 : std_logic := '0';
signal FullAdderModule_TopLevel_FullAdderModule_FullAdder_L17F29T70_Expr : std_logic := '0';
signal FullAdderModule_TopLevel_FullAdderModule_FullAdder_L17F29T70_Expr_1 : std_logic := '0';
signal FullAdderModule_TopLevel_FullAdderModule_FullAdder_L17F29T70_Expr_2 : std_logic := '0';
signal FullAdderModule_TopLevel_FullAdderModule_FullAdder_L17F30T49_Expr : std_logic := '0';
signal FullAdderModule_TopLevel_FullAdderModule_FullAdder_L17F30T49_Expr_1 : std_logic := '0';
signal FullAdderModule_TopLevel_FullAdderModule_FullAdder_L17F30T49_Expr_2 : std_logic := '0';
signal FullAdderModule_TopLevel_FullAdderModule_FullAdder_L17F55T69_Expr : std_logic := '0';
signal FullAdderModule_TopLevel_FullAdderModule_FullAdder_L17F55T69_Expr_1 : std_logic := '0';
signal FullAdderModule_TopLevel_FullAdderModule_FullAdder_L17F55T69_Expr_2 : std_logic := '0';
begin

process(FullAdderModule_TopLevel_FullAdderModule_FullAdder_L14F27T46_Expr_1, FullAdderModule_TopLevel_FullAdderModule_FullAdder_L14F27T46_Expr_2)
begin
FullAdderModule_TopLevel_FullAdderModule_FullAdder_L14F27T46_Expr <= FullAdderModule_TopLevel_FullAdderModule_FullAdder_L14F27T46_Expr_1 XOR FullAdderModule_TopLevel_FullAdderModule_FullAdder_L14F27T46_Expr_2;

    end process;

process(FullAdderModule_TopLevel_FullAdderModule_FullAdder_L16F26T40_Expr_1, FullAdderModule_TopLevel_FullAdderModule_FullAdder_L16F26T40_Expr_2)
begin
FullAdderModule_TopLevel_FullAdderModule_FullAdder_L16F26T40_Expr <= FullAdderModule_TopLevel_FullAdderModule_FullAdder_L16F26T40_Expr_1 XOR FullAdderModule_TopLevel_FullAdderModule_FullAdder_L16F26T40_Expr_2;

    end process;

process(FullAdderModule_TopLevel_FullAdderModule_FullAdder_L17F29T70_Expr_1, FullAdderModule_TopLevel_FullAdderModule_FullAdder_L17F29T70_Expr_2)
begin
FullAdderModule_TopLevel_FullAdderModule_FullAdder_L17F29T70_Expr <= FullAdderModule_TopLevel_FullAdderModule_FullAdder_L17F29T70_Expr_1 OR FullAdderModule_TopLevel_FullAdderModule_FullAdder_L17F29T70_Expr_2;

    end process;

process(FullAdderModule_TopLevel_FullAdderModule_FullAdder_L17F30T49_Expr_1, FullAdderModule_TopLevel_FullAdderModule_FullAdder_L17F30T49_Expr_2)
begin
FullAdderModule_TopLevel_FullAdderModule_FullAdder_L17F30T49_Expr <= FullAdderModule_TopLevel_FullAdderModule_FullAdder_L17F30T49_Expr_1 AND FullAdderModule_TopLevel_FullAdderModule_FullAdder_L17F30T49_Expr_2;

    end process;

process(FullAdderModule_TopLevel_FullAdderModule_FullAdder_L17F55T69_Expr_1, FullAdderModule_TopLevel_FullAdderModule_FullAdder_L17F55T69_Expr_2)
begin
FullAdderModule_TopLevel_FullAdderModule_FullAdder_L17F55T69_Expr <= FullAdderModule_TopLevel_FullAdderModule_FullAdder_L17F55T69_Expr_1 AND FullAdderModule_TopLevel_FullAdderModule_FullAdder_L17F55T69_Expr_2;

    end process;
-- Top-level entity connections
process(FullAdderModule_TopLevel_FullAdderModuleCOut, FullAdderModule_TopLevel_FullAdderModuleO, FullAdderModuleA, FullAdderModuleB, FullAdderModuleCIn)
begin
	FullAdderModule_TopLevel_FullAdderModuleA <= FullAdderModuleA;
	FullAdderModule_TopLevel_FullAdderModuleB <= FullAdderModuleB;
	FullAdderModule_TopLevel_FullAdderModuleCIn <= FullAdderModuleCIn;
FullAdderModuleO <= FullAdderModule_TopLevel_FullAdderModuleO;
FullAdderModuleCOut <= FullAdderModule_TopLevel_FullAdderModuleCOut;
end process;
process(FullAdderModule_TopLevel_FullAdderModule_A, FullAdderModule_TopLevel_FullAdderModule_B, FullAdderModule_TopLevel_FullAdderModule_CIn, FullAdderModule_TopLevel_FullAdderModule_COut, FullAdderModule_TopLevel_FullAdderModule_FullAdder_L14F27T46_Expr, FullAdderModule_TopLevel_FullAdderModule_FullAdder_L16F26T40_Expr, FullAdderModule_TopLevel_FullAdderModule_FullAdder_L17F29T70_Expr, FullAdderModule_TopLevel_FullAdderModule_FullAdder_L17F30T49_Expr, FullAdderModule_TopLevel_FullAdderModule_FullAdder_L17F55T69_Expr, FullAdderModule_TopLevel_FullAdderModule_Inputs_A, FullAdderModule_TopLevel_FullAdderModule_Inputs_B, FullAdderModule_TopLevel_FullAdderModule_Inputs_CIn, FullAdderModule_TopLevel_FullAdderModule_O, FullAdderModule_TopLevel_FullAdderModule_P, FullAdderModule_TopLevel_FullAdderModuleA, FullAdderModule_TopLevel_FullAdderModuleB, FullAdderModule_TopLevel_FullAdderModuleCIn)
begin
FullAdderModule_TopLevel_FullAdderModule_A <= FullAdderModule_TopLevel_FullAdderModuleA;
FullAdderModule_TopLevel_FullAdderModule_B <= FullAdderModule_TopLevel_FullAdderModuleB;
FullAdderModule_TopLevel_FullAdderModule_CIn <= FullAdderModule_TopLevel_FullAdderModuleCIn;
FullAdderModule_TopLevel_FullAdderModuleO <= FullAdderModule_TopLevel_FullAdderModule_O;
FullAdderModule_TopLevel_FullAdderModuleCOut <= FullAdderModule_TopLevel_FullAdderModule_COut;
FullAdderModule_TopLevel_FullAdderModule_FullAdder_L14F27T46_Expr_1 <= FullAdderModule_TopLevel_FullAdderModule_Inputs_A;
FullAdderModule_TopLevel_FullAdderModule_FullAdder_L14F27T46_Expr_2 <= FullAdderModule_TopLevel_FullAdderModule_Inputs_B;
FullAdderModule_TopLevel_FullAdderModule_FullAdder_L16F26T40_Expr_1 <= FullAdderModule_TopLevel_FullAdderModule_P;
FullAdderModule_TopLevel_FullAdderModule_FullAdder_L16F26T40_Expr_2 <= FullAdderModule_TopLevel_FullAdderModule_Inputs_CIn;
FullAdderModule_TopLevel_FullAdderModule_FullAdder_L17F29T70_Expr_1 <= FullAdderModule_TopLevel_FullAdderModule_FullAdder_L17F30T49_Expr;
FullAdderModule_TopLevel_FullAdderModule_FullAdder_L17F29T70_Expr_2 <= FullAdderModule_TopLevel_FullAdderModule_FullAdder_L17F55T69_Expr;
FullAdderModule_TopLevel_FullAdderModule_FullAdder_L17F30T49_Expr_1 <= FullAdderModule_TopLevel_FullAdderModule_Inputs_A;
FullAdderModule_TopLevel_FullAdderModule_FullAdder_L17F30T49_Expr_2 <= FullAdderModule_TopLevel_FullAdderModule_Inputs_B;
FullAdderModule_TopLevel_FullAdderModule_FullAdder_L17F55T69_Expr_1 <= FullAdderModule_TopLevel_FullAdderModule_P;
FullAdderModule_TopLevel_FullAdderModule_FullAdder_L17F55T69_Expr_2 <= FullAdderModule_TopLevel_FullAdderModule_Inputs_CIn;
FullAdderModule_TopLevel_FullAdderModule_Inputs_A <= FullAdderModule_TopLevel_FullAdderModule_A;
FullAdderModule_TopLevel_FullAdderModule_Inputs_B <= FullAdderModule_TopLevel_FullAdderModule_B;
FullAdderModule_TopLevel_FullAdderModule_Inputs_CIn <= FullAdderModule_TopLevel_FullAdderModule_CIn;
FullAdderModule_TopLevel_FullAdderModule_P <= FullAdderModule_TopLevel_FullAdderModule_FullAdder_L14F27T46_Expr;
FullAdderModule_TopLevel_FullAdderModule_O <= FullAdderModule_TopLevel_FullAdderModule_FullAdder_L16F26T40_Expr;
FullAdderModule_TopLevel_FullAdderModule_COut <= FullAdderModule_TopLevel_FullAdderModule_FullAdder_L17F29T70_Expr;
end process;
-- [BEGIN USER ARCHITECTURE]
-- [END USER ARCHITECTURE]
end architecture;
