-- PLEASE READ THIS, IT MAY SAVE YOU SOME TIME AND MONEY, THANK YOU!
-- * This file was generated by Quokka FPGA Toolkit.
-- * Generated code is your property, do whatever you want with it
-- * Place custom code between [BEGIN USER ***] and [END USER ***].
-- * CAUTION: All code outside of [USER] scope is subject to regeneration.
-- * Bad things happen sometimes in developer's life,
--   it is recommended to use source control management software (e.g. git, bzr etc) to keep your custom code safe'n'sound.
-- * Internal structure of code is subject to change.
--   You can use some of signals in custom code, but most likely they will not exist in future (e.g. will get shorter or gone completely)
-- * Please send your feedback, comments, improvement ideas etc. to evmuryshkin@gmail.com
-- * Visit https://github.com/EvgenyMuryshkin/QuokkaEvaluation to access latest version of playground
-- 
-- DISCLAIMER:
--   Code comes AS-IS, it is your responsibility to make sure it is working as expected
--   no responsibility will be taken for any loss or damage caused by use of Quokka toolkit.
-- 
-- System configuration name is InverterModule_TopLevel, clock frequency is 1Hz, Top-level
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

use work.Quokka.all;

entity InverterModule_TopLevel is
    port
    (
-- [BEGIN USER PORTS]
-- [END USER PORTS]

InverterModuleInput : in  std_logic;
InverterModuleOutput : out  std_logic
    );
end entity;

-- FSM summary
-- Packages
architecture rtl of InverterModule_TopLevel is
-- [BEGIN USER SIGNALS]
-- [END USER SIGNALS]
constant HiSignal : std_logic := '1';
constant LoSignal : std_logic := '0';
signal InverterModule_TopLevel_InverterModuleInput : std_logic := '0';
signal InverterModule_TopLevel_InverterModuleOutput : std_logic := '0';
signal InverterModule_TopLevel_InverterModule_Input : std_logic := '0';
signal InverterModule_TopLevel_InverterModule_Output : std_logic := '0';
constant InverterModule_TopLevel_InverterModule_Zero : std_logic := '0';
constant InverterModule_TopLevel_InverterModule_One : std_logic := '1';
constant InverterModule_TopLevel_InverterModule_true : std_logic := '1';
constant InverterModule_TopLevel_InverterModule_false : std_logic := '0';
signal InverterModule_TopLevel_InverterModule_Inputs_Input : std_logic := '0';
signal InverterModule_TopLevel_InverterModule_InverterModule_L7F31T44_Expr : std_logic := '0';
signal InverterModule_TopLevel_InverterModule_InverterModule_L7F31T44_Expr_1 : std_logic := '0';
begin

process(InverterModule_TopLevel_InverterModule_InverterModule_L7F31T44_Expr_1)
begin
InverterModule_TopLevel_InverterModule_InverterModule_L7F31T44_Expr <= NOT InverterModule_TopLevel_InverterModule_InverterModule_L7F31T44_Expr_1;

    end process;
-- Top-level entity connections
process(InverterModule_TopLevel_InverterModuleOutput, InverterModuleInput)
begin
	InverterModule_TopLevel_InverterModuleInput <= InverterModuleInput;
InverterModuleOutput <= InverterModule_TopLevel_InverterModuleOutput;
end process;
process(InverterModule_TopLevel_InverterModule_Input, InverterModule_TopLevel_InverterModule_Inputs_Input, InverterModule_TopLevel_InverterModule_InverterModule_L7F31T44_Expr, InverterModule_TopLevel_InverterModule_Output, InverterModule_TopLevel_InverterModuleInput)
begin
InverterModule_TopLevel_InverterModule_Input <= InverterModule_TopLevel_InverterModuleInput;
InverterModule_TopLevel_InverterModuleOutput <= InverterModule_TopLevel_InverterModule_Output;
InverterModule_TopLevel_InverterModule_InverterModule_L7F31T44_Expr_1 <= InverterModule_TopLevel_InverterModule_Inputs_Input;
InverterModule_TopLevel_InverterModule_Inputs_Input <= InverterModule_TopLevel_InverterModule_Input;
InverterModule_TopLevel_InverterModule_Output <= InverterModule_TopLevel_InverterModule_InverterModule_L7F31T44_Expr;
end process;
-- [BEGIN USER ARCHITECTURE]
-- [END USER ARCHITECTURE]
end architecture;
